{% set name = "python-cmr" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/python-cmr-{{ version }}.tar.gz
  sha256: d1c3fa15053193cfdea667252da1152f81a8ecf8ac9a18362cdcfe549d48a1b5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - requests

test:
  imports:
    - cmr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nasa/python_cmr
  summary: Python wrapper to the NASA Common Metadata Repository (CMR) API.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rsignell-usgs
