{% set name = "python-cmr" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 16d61f7fa1ac24c3cbf484723244482934b71e04434093b4bb5663ae934a19c6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<4.0
    - poetry >=0.12
  run:
    - python >=3.8,<4.0
    - requests >=2.26.0,<3.0.0
    - python-dateutil >=2.8.2,<3.0.0
    - typing-extensions >=4.11.0,<5.0.0

test:
  imports:
    - cmr
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nasa/python_cmr
  summary: Python wrapper to the NASA Common Metadata Repository (CMR) API.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - chuckwondo
    - mfisher87
    - rsignell-usgs
    - betolink
    - frankinspace
